# Generated by Django 4.2.1 on 2023-06-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CvForm',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo_url', models.CharField(max_length=3000)),
                ('position', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=50)),
                ('salary_taxes', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('how_old_ad', models.CharField(max_length=50)),
                ('ad_link', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='CVscraper.cvform')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
