# Generated by Django 4.2.1 on 2023-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvform',
            name='work_area',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
