# Generated by Django 4.2.1 on 2023-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVscraper', '0002_cvform_work_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(to='CVscraper.cvform'),
        ),
    ]
