# Generated by Django 4.2.1 on 2023-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVscraper', '0003_remove_profile_likes_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='CVscraper.cvform'),
        ),
    ]
